// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает информацию о токене из заголовка Authorization",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Получить информацию о токене",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Token"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/bots": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список всех ботов (требуется админский токен)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bots"
                ],
                "summary": "Получить всех ботов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Bot"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт нового бота/робота (требуется админский токен)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bots"
                ],
                "summary": "Создать бота",
                "parameters": [
                    {
                        "description": "Данные бота",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bot_handler.CreateBotRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Bot"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/bots/{bot_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает информацию о боте по ID (требуется админский токен)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bots"
                ],
                "summary": "Получить бота",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID бота (UUID)",
                        "name": "bot_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Bot"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет данные бота (требуется админский токен)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bots"
                ],
                "summary": "Обновить бота",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID бота (UUID)",
                        "name": "bot_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновлённые данные",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bot_handler.UpdateBotRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Bot"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Полностью удаляет бота из базы данных (требуется админский токен)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bots"
                ],
                "summary": "Удалить бота",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID бота (UUID)",
                        "name": "bot_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/eff-runs": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт новую запись о запуске бота (требуется авторизация, только для обычных токенов с bot_id)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "eff_runs"
                ],
                "summary": "Создать запись о запуске",
                "parameters": [
                    {
                        "description": "Данные о запуске",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/eff_run_handler.CreateEffRunRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.EffRun"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/logs": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт новый лог от имени текущего бота (требуется авторизация)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Создать лог",
                "parameters": [
                    {
                        "description": "Данные лога",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/log_handler.CreateLogRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Log"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/owners": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список всех владельцев (требуется админский токен)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "owners"
                ],
                "summary": "Получить всех владельцев",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Owner"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт нового владельца (требуется админский токен)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "owners"
                ],
                "summary": "Создать владельца",
                "parameters": [
                    {
                        "description": "Данные владельца",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/owner_handler.CreateOwnerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Owner"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/owners/{owner_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает информацию о владельце по ID (требуется админский токен)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "owners"
                ],
                "summary": "Получить владельца",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID владельца (UUID)",
                        "name": "owner_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Owner"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет данные владельца (требуется админский токен)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "owners"
                ],
                "summary": "Обновить владельца",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID владельца (UUID)",
                        "name": "owner_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновлённые данные",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/owner_handler.UpdateOwnerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Owner"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Полностью удаляет владельца из базы данных (требуется админский токен)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "owners"
                ],
                "summary": "Удалить владельца",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID владельца (UUID)",
                        "name": "owner_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/tokens": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт новый токен аутентификации для указанного бота (требуется админский токен)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Создать новый токен",
                "parameters": [
                    {
                        "description": "Данные для создания токена",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth_handler.CreateTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth_handler.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/tokens/{token_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет название существующего токена (требуется админский токен)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Обновить токен",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID токена (UUID)",
                        "name": "token_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новое название токена",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth_handler.UpdateTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Полностью удаляет токен из базы данных (требуется админский токен)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Удалить токен",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID токена (UUID)",
                        "name": "token_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/tokens/{token_id}/deactivate": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Деактивирует токен (мягкое удаление, токен перестаёт работать, требуется админский токен)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Деактивировать токен",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID токена (UUID)",
                        "name": "token_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth_handler.CreateTokenRequest": {
            "type": "object",
            "required": [
                "token_name"
            ],
            "properties": {
                "bot_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_admin": {
                    "type": "boolean",
                    "example": false
                },
                "token_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Production Server"
                }
            }
        },
        "auth_handler.TokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "auth_handler.UpdateTokenRequest": {
            "type": "object",
            "required": [
                "token_name"
            ],
            "properties": {
                "token_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Production Server v2"
                }
            }
        },
        "bot_handler.CreateBotRequest": {
            "type": "object",
            "required": [
                "bot_type",
                "code",
                "language",
                "name"
            ],
            "properties": {
                "bot_type": {
                    "type": "string",
                    "enum": [
                        "AI",
                        "Backend",
                        "Frontend",
                        "Robot"
                    ],
                    "example": "Backend"
                },
                "code": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "BOT_001"
                },
                "description": {
                    "type": "string",
                    "example": "Бот для обработки сообщений"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "language": {
                    "type": "string",
                    "enum": [
                        "Python",
                        "Go",
                        "N8N",
                        "PIX",
                        "JS",
                        "C",
                        "Other"
                    ],
                    "example": "Python"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "Telegram Bot"
                },
                "owner_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "telegram",
                        "bot"
                    ]
                }
            }
        },
        "bot_handler.UpdateBotRequest": {
            "type": "object",
            "properties": {
                "bot_type": {
                    "type": "string",
                    "enum": [
                        "AI",
                        "Backend",
                        "Frontend",
                        "Robot"
                    ],
                    "example": "AI"
                },
                "code": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "BOT_002"
                },
                "description": {
                    "type": "string",
                    "example": "Обновлённое описание"
                },
                "is_active": {
                    "type": "boolean",
                    "example": false
                },
                "language": {
                    "type": "string",
                    "enum": [
                        "Python",
                        "Go",
                        "N8N",
                        "PIX",
                        "JS",
                        "C",
                        "Other"
                    ],
                    "example": "Go"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "Discord Bot"
                },
                "owner_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "discord",
                        "ai"
                    ]
                }
            }
        },
        "eff_run_handler.CreateEffRunRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "extra": {
                    "$ref": "#/definitions/models.JSONB"
                },
                "host": {
                    "type": "string",
                    "example": "server-01"
                },
                "period_from": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "period_to": {
                    "type": "string",
                    "example": "2024-01-01T01:00:00Z"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "success",
                        "warning",
                        "error"
                    ],
                    "example": "success"
                }
            }
        },
        "log_handler.CreateLogRequest": {
            "type": "object",
            "required": [
                "msg",
                "status"
            ],
            "properties": {
                "msg": {
                    "type": "string",
                    "minLength": 1,
                    "example": "Операция выполнена успешно"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "Debug",
                        "Info",
                        "Warning",
                        "Error",
                        "Critical"
                    ],
                    "example": "Info"
                }
            }
        },
        "models.Bot": {
            "type": "object",
            "required": [
                "bot_type",
                "code",
                "language",
                "name"
            ],
            "properties": {
                "bot_type": {
                    "description": "Тип бота (AI, Backend, Frontend, Robot)",
                    "type": "string",
                    "enum": [
                        "AI",
                        "Backend",
                        "Frontend",
                        "Robot"
                    ],
                    "example": "Backend"
                },
                "code": {
                    "description": "Уникальный код бота для идентификации",
                    "type": "string",
                    "example": "BOT_001"
                },
                "created_at": {
                    "description": "Дата и время создания записи",
                    "type": "string",
                    "example": "2023-01-15T12:00:00Z"
                },
                "description": {
                    "description": "Подробное описание функционала бота",
                    "type": "string",
                    "example": "Бот для обработки сообщений"
                },
                "id": {
                    "description": "Уникальный идентификатор бота (UUID)",
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "description": "Активен ли бот",
                    "type": "boolean",
                    "example": true
                },
                "language": {
                    "description": "Основной язык или технология реализации",
                    "type": "string",
                    "enum": [
                        "Python",
                        "Go",
                        "N8N",
                        "PIX",
                        "JS",
                        "C",
                        "Other"
                    ],
                    "example": "Python"
                },
                "name": {
                    "description": "Название бота",
                    "type": "string",
                    "example": "Telegram Bot"
                },
                "owner_id": {
                    "description": "ID владельца бота",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "tags": {
                    "description": "Массив тегов для классификации",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "telegram",
                        "automation"
                    ]
                },
                "updated_at": {
                    "description": "Дата и время последнего обновления",
                    "type": "string",
                    "example": "2023-01-15T12:00:00Z"
                }
            }
        },
        "models.EffRun": {
            "type": "object",
            "required": [
                "bot_id"
            ],
            "properties": {
                "bot_id": {
                    "description": "ID бота",
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "created_at": {
                    "description": "Дата и время создания записи",
                    "type": "string",
                    "example": "2023-01-15T12:00:00Z"
                },
                "extra": {
                    "description": "Дополнительные метаданные в формате JSON",
                    "type": "object"
                },
                "host": {
                    "description": "Хост, на котором выполнялся бот",
                    "type": "string",
                    "example": "server-01"
                },
                "id": {
                    "description": "Уникальный идентификатор запуска",
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "period_from": {
                    "description": "Начало периода выполнения",
                    "type": "string",
                    "example": "2023-01-15T10:00:00Z"
                },
                "period_to": {
                    "description": "Конец периода выполнения",
                    "type": "string",
                    "example": "2023-01-15T12:00:00Z"
                },
                "status": {
                    "description": "Статус выполнения запуска",
                    "type": "string",
                    "enum": [
                        "success",
                        "warning",
                        "error"
                    ],
                    "example": "success"
                }
            }
        },
        "models.JSONB": {
            "type": "object",
            "additionalProperties": true
        },
        "models.Log": {
            "type": "object",
            "required": [
                "msg"
            ],
            "properties": {
                "bot_id": {
                    "description": "ID бота, отправившего лог",
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "created_at": {
                    "description": "Дата и время создания лога",
                    "type": "string",
                    "example": "2023-01-15T12:00:00Z"
                },
                "id": {
                    "description": "Уникальный идентификатор лога",
                    "type": "integer",
                    "example": 12345
                },
                "msg": {
                    "description": "Текст сообщения лога",
                    "type": "string",
                    "example": "Операция выполнена успешно"
                },
                "status": {
                    "description": "Уровень лога",
                    "type": "string",
                    "enum": [
                        "Debug",
                        "Info",
                        "Warning",
                        "Error",
                        "Critical"
                    ],
                    "example": "Info"
                }
            }
        },
        "models.Owner": {
            "type": "object",
            "required": [
                "full_name"
            ],
            "properties": {
                "created_at": {
                    "description": "Дата и время создания записи",
                    "type": "string",
                    "example": "2023-01-15T12:00:00Z"
                },
                "full_name": {
                    "description": "Полное имя владельца",
                    "type": "string",
                    "example": "Иван Иванов"
                },
                "id": {
                    "description": "Уникальный идентификатор владельца (UUID)",
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "description": "Активен ли владелец",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.Token": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "bot_id": {
                    "description": "ID бота, для которого создан токен (NULL для админских токенов)",
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "created_at": {
                    "description": "Дата и время создания токена",
                    "type": "string",
                    "example": "2023-01-15T12:00:00Z"
                },
                "id": {
                    "description": "Уникальный идентификатор токена (используется как API ключ)",
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_active": {
                    "description": "Активен ли токен",
                    "type": "boolean",
                    "example": true
                },
                "is_admin": {
                    "description": "Обладает ли токен административными правами",
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "description": "Название токена",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Production Server"
                }
            }
        },
        "owner_handler.CreateOwnerRequest": {
            "type": "object",
            "required": [
                "full_name"
            ],
            "properties": {
                "full_name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "Иван Иванов"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "owner_handler.UpdateOwnerRequest": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2,
                    "example": "Иван Петров"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Введите токен в формате: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.alexmayka.ru",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "Logging API",
	Description:      "API для управления токенами и логами ботов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
